apiVersion: {{ template "redmine.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "redmine.fullname" . }}
  labels: {{- include "redmine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "redmine.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{- include "redmine.labels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations: {{- include "redmine.tplValue" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
{{- include "redmine.imagePullSecrets" . | indent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- include "redmine.tplValue" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "redmine.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "redmine.tplValue" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "redmine.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "redmine.fullname" . }}
          image: {{ template "redmine.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.extraVars }}
            {{- toYaml .Values.extraVars | nindent 12 }}
            {{- end }}
            {{- if eq .Values.databaseType "mariadb" }}
            - name: REDMINE_DB_MYSQL
            {{- if .Values.mariadb.enabled }}
              value: {{ template "redmine.mariadb.fullname" . }}
            - name: REDMINE_DB_NAME
              value: {{ .Values.mariadb.db.name | quote }}
            - name: REDMINE_DB_USERNAME
              value: {{ .Values.mariadb.db.user | quote }}
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.mariadb.fullname" . }}
                  key: mariadb-password
            {{- else }}
              value: {{ .Values.externalDatabase.host | quote }}
            {{- end }}
            {{- else if eq .Values.databaseType "postgresql" }}
            - name: REDMINE_DB_POSTGRES
            {{- if .Values.postgresql.enabled }}
              value: {{ template "redmine.postgresql.fullname" . }}
            - name: REDMINE_DB_NAME
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            - name: REDMINE_DB_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.postgresql.fullname" . }}
                  key: postgresql-password
            {{- else }}
              value: {{ .Values.externalDatabase.host | quote }}
            {{- end }}
            {{- end }}
            {{- if or (and (eq .Values.databaseType "mariadb") (not .Values.mariadb.enabled)) (and (eq .Values.databaseType "postgresql") (not .Values.postgresql.enabled)) }}
            - name: REDMINE_DB_NAME
              value: {{ .Values.externalDatabase.name | quote }}
            - name: REDMINE_DB_USERNAME
              value: {{ .Values.externalDatabase.user | quote }}
            - name: REDMINE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.secretName" . }}
                  key: external-db-password
            - name: REDMINE_DB_PORT_NUMBER
              value: {{ .Values.externalDatabase.port | quote }}
            {{- end }}
            - name: REDMINE_EMAIL
              value: {{ .Values.redmineEmail | quote }}
            - name: REDMINE_LANG
              value: {{ .Values.redmineLanguage | quote }}
            {{- if .Values.smtpHost }}
            - name: SMTP_HOST
              value: {{ .Values.smtpHost | quote }}
            {{- end }}
            {{- if .Values.smtpPort }}
            - name: SMTP_PORT
              value: {{ .Values.smtpPort | quote }}
            {{- end }}
            {{- if .Values.smtpUser }}
            - name: SMTP_USER
              value: {{ .Values.smtpUser | quote }}
            {{- end }}
            {{- if .Values.smtpPassword }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.secretName" . }}
                  key: smtp-password
            {{- end }}
            {{- if .Values.smtpTls }}
            - name: SMTP_TLS
              value: {{ .Values.smtpTls | quote }}
            {{- end }}
            {{- if .Values.pluginsMigrate }}
            - name: REDMINE_PLUGINS_MIGRATE
              value: "true"
            {{- end }}
          command: 
            - /bin/bash
            - "-c"
            - "--"
          args:
            - "if [ -e /root/.ssh/id_rsa ]; then mkdir /home/redmine/.ssh; cat /root/.ssh/id_rsa > /home/redmine/.ssh/id_rsa; chown -R redmine:redmine /home/redmine/.ssh; chmod 600 /home/redmine/.ssh/id_rsa; ls -la /home/redmine/.ssh/;fi; /docker-entrypoint.sh rails server -b 0.0.0.0"
          ports:
            - name: http-redmine
              containerPort: 3000
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http-redmine
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http-redmine
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: redmine-data
              mountPath: /usr/src/redmine/files
              subPath: files
            - name: redmine-data
              mountPath: /usr/src/redmine/plugins
              subPath: plugins
            {{- if .Values.git.enabled }}
            - name: ssh-private-key
              mountPath: /root/.ssh
            {{- end }}
        {{- if .Values.mailReceiver.enabled }}
        - name: {{ template "redmine.mailReceiver.fullname" . }}-receiver
          image: {{ template "redmine.mailReceiver.image" . }}
          imagePullPolicy: {{ .Values.mailReceiver.image.pullPolicy | quote }}
          command:
            - bash
          args:
            - -c
            - while true; do /cj/receive.sh; sleep {{ .Values.mailReceiver.checkPeriod }}; done
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: mail-receiver
              mountPath: /cj
            - name: redmine-data
              mountPath: /usr/src/redmine/files
              subPath: files
          env:
            {{- if eq .Values.databaseType "mariadb" }}
            - name: REDMINE_MAIL_RECEIVER_DB_MYSQL
            {{- if .Values.mariadb.enabled }}
              value: {{ template "redmine.mariadb.fullname" . }}
            - name: REDMINE_MAIL_RECEIVER_DB_DATABASE
              value: {{ .Values.mariadb.db.name | quote }}
            - name: REDMINE_MAIL_RECEIVER_DB_USERNAME
              value: {{ .Values.mariadb.db.user | quote }}
            - name: REDMINE_MAIL_RECEIVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.mariadb.fullname" . }}
                  key: mariadb-password
            - name: REDMINE_MAIL_RECEIVER_DB_PORT
              value: "3306"
            {{- else }}
              value: {{ .Values.externalDatabase.host | quote }}
            {{- end }}
            {{- else if eq .Values.databaseType "postgresql" }}
            - name: REDMINE_MAIL_RECEIVER_DB_POSTGRES
            {{- if .Values.postgresql.enabled }}
              value: {{ template "redmine.postgresql.fullname" . }}
            - name: REDMINE_MAIL_RECEIVER_DB_DATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            - name: REDMINE_MAIL_RECEIVER_DB_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: REDMINE_MAIL_RECEIVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.postgresql.fullname" . }}
                  key: postgresql-password
            - name: REDMINE_MAIL_RECEIVER_DB_PORT
              value: "5432"
            {{- else }}
              value: {{ .Values.externalDatabase.host | quote }}
            {{- end }}
            {{- end }}
            {{- if or (and (eq .Values.databaseType "mariadb") (not .Values.mariadb.enabled)) (and (eq .Values.databaseType "postgresql") (not .Values.postgresql.enabled)) }}
            - name: REDMINE_MAIL_RECEIVER_DB_DATABASE
              value: {{ .Values.externalDatabase.name | quote }}
            - name: REDMINE_MAIL_RECEIVER_DB_USERNAME
              value: {{ .Values.externalDatabase.user | quote }}
            - name: REDMINE_MAIL_RECEIVER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.secretName" . }}
                  key: external-db-password
            - name: REDMINE_MAIL_RECEIVER_DB_PORT
              value: {{ .Values.externalDatabase.port | quote }}
            {{- end }}
            - name: REDMINE_MAIL_RECEIVER_HOST
              value: {{ .Values.mailReceiver.host | quote }}
            - name: REDMINE_MAIL_RECEIVER_PORT
              value: {{ .Values.mailReceiver.port | quote }}
            - name: REDMINE_MAIL_RECEIVER_USERNAME
              value: {{ .Values.mailReceiver.username | quote }}
            - name: REDMINE_MAIL_RECEIVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redmine.secretName" . }}
                  key: mail-receiver-password
            - name: REDMINE_MAIL_RECEIVER_USE_SSL
              value: {{ .Values.mailReceiver.ssl | quote }}
            - name: REDMINE_MAIL_RECEIVER_STARTTLS
              value: {{ .Values.mailReceiver.startTLS | quote }}
            - name: REDMINE_MAIL_RECEIVER_IMAP_FOLDER
              value: {{ .Values.mailReceiver.imapFolder | quote }}
            - name: REDMINE_MAIL_RECEIVER_IMAP_MOVE_ON_SUCCESS
              value: {{ .Values.mailReceiver.moveOnSuccess | quote }}
            - name: REDMINE_MAIL_RECEIVER_IMAP_MOVE_ON_FAILURE
              value: {{ .Values.mailReceiver.moveOnFailure | quote }}
            - name: REDMINE_MAIL_RECEIVER_UNKNOWN_USER_ACTION
              value: {{ .Values.mailReceiver.unknownUserAction | quote }}
            - name: REDMINE_MAIL_RECEIVER_NO_PERMISSION_CHECK
              value: {{ .Values.mailReceiver.noPermissionCheck | quote }}
            - name: REDMINE_MAIL_RECEIVER_NO_ACCOUNT_NOTICE
              value: {{ .Values.mailReceiver.noAccountNotice | quote }}
            - name: REDMINE_MAIL_RECEIVER_DEFAULT_GROUP
              value: {{ .Values.mailReceiver.defaultGroup | quote }}
            - name: REDMINE_MAIL_RECEIVER_PROJECT
              value: {{ .Values.mailReceiver.project | quote }}
            - name: REDMINE_MAIL_RECEIVER_PROJECT_FROM_SUBADDRESS
              value: {{ .Values.mailReceiver.projectFromSubaddress | quote }}
            - name: REDMINE_MAIL_RECEIVER_STATUS
              value: {{ .Values.mailReceiver.status | quote }}
            - name: REDMINE_MAIL_RECEIVER_TRACKER
              value: {{ .Values.mailReceiver.tracker | quote }}
            - name: REDMINE_MAIL_RECEIVER_CATEGORY
              value: {{ .Values.mailReceiver.category | quote }}
            - name: REDMINE_MAIL_RECEIVER_PRIORITY
              value: {{ .Values.mailReceiver.priority | quote }}
            - name: REDMINE_MAIL_RECEIVER_ASSIGNED_TO
              value: {{ .Values.mailReceiver.assignedTo | quote }}
            - name: REDMINE_MAIL_RECEIVER_ALLOW_OVERRIDE
              value: {{ .Values.mailReceiver.allowOverride | quote }}
            - name: REDMINE_MAIL_RECEIVER_SECRET_KEY_BASE
              value: {{ randAlphaNum 64 | quote }}
            - name: REDMINE_MAIL_RECEIVER_PROTOCOL
              value: {{ .Values.mailReceiver.mailProtocol | quote }}
            - name: REDMINE_MAIL_RECEIVER_POP3_DELETE_UNPROCESSED
              value: {{ .Values.mailReceiver.moveOnFailure | quote }}
        {{- end }}
        {{- if .Values.stunnel.enabled }}
        - name: {{ template "redmine.fullname" . }}-stunnel
          image: {{ .Values.stunnel.image.repository }}:{{ .Values.stunnel.image.tag }}
          imagePullPolicy: {{ .Values.stunnel.image.pullPolicy | quote }}
          volumeMounts:
            - name: stunnel-certs
              mountPath: /etc/stunnel/stunnel.key
              subPath: stunnel.key
            - name: stunnel-certs
              mountPath: /etc/stunnel/stunnel.pem
              subPath: stunnel.pem
          env:
            {{ range $name, $value := .Values.stunnel.envVars }}
            - name: STUNNEL_{{ upper $name }}
              value: {{ $value | quote }}
            {{ end }}
        {{- end }}
      volumes:
        - name: redmine-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "redmine.fullname" .) }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.git.enabled }}
        - name: ssh-private-key
          secret:
            secretName: {{ template "redmine.fullname" . }}
            defaultMode: 0666
            items: 
            - key: "ssh-private-key"
              path: "id_rsa"
        {{- end }}
        {{- if .Values.mailReceiver.enabled }}
        - name: mail-receiver
          configMap:
            name: {{ template "redmine.fullname" . }}-receiver
            defaultMode: 0744
        {{- end }}
        {{- if .Values.stunnel.enabled }}
        - name: stunnel-certs
          secret:
            secretName: {{ template "redmine.fullname" . }}-stunnel
            defaultMode: 0666
        {{- end }}
