{{ if .Values.stunnel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redmine.fullname" . }}-stunnel
  labels: {{- include "redmine.labels" . | nindent 4 }}
type: Opaque
data:
  stunnel.key: {{ .Values.stunnel.key | b64enc | quote }}
  stunnel.pem: {{ .Values.stunnel.pem | b64enc | quote }}
{{ end }}
